echo 1-A ; sleep 1 ; echo 
echo 2-A ; sleep 2 ; echo 
echo 3-A ; sleep 3 ; echo 
echo 4-A ; sleep 4 ; echo 
echo 5-A ; sleep 5 ; echo 
echo 1-B ; sleep 1 ; echo 
echo 2-B ; sleep 2 ; echo 
echo 3-B ; sleep 3 ; echo 
echo 4-B ; sleep 4 ; echo 
echo 5-B ; sleep 5 ; echo 
echo 1-C ; sleep 1 ; echo 
echo 2-C ; sleep 2 ; echo 
echo 3-C ; sleep 3 ; echo 
echo 4-C ; sleep 4 ; echo 
echo 5-C ; sleep 5 ; echo 
echo 1-D ; sleep 1 ; echo 
echo 2-D ; sleep 2 ; echo 
echo 3-D ; sleep 3 ; echo 
echo 4-D ; sleep 4 ; echo 
echo 5-D ; sleep 5 ; echo 
echo 1-E ; sleep 1 ; echo 
echo 2-E ; sleep 2 ; echo 
echo 3-E ; sleep 3 ; echo 
echo 4-E ; sleep 4 ; echo 
echo 5-E ; sleep 5 ; echo 
